/**
 * JamApi
 * Api for JamServe
 *
 * OpenAPI spec version: 0.2.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ID} from 'src/@jam/model/iD';
import {UserRoles} from 'src/@jam/model/userRoles';

export interface SessionUser {
  id: ID;
  /**
   * User Name
   */
  name: string;
  roles: UserRoles;
}
