/**
 * JamApi
 * Api for JamServe
 *
 * OpenAPI spec version: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CredentialsArgs { 
    /**
     * User password
     */
    password: string;
    /**
     * User name
     */
    username: string;
    /**
     * User client
     */
    client: string;
    /**
     * Generate JSON Web Token
     */
    jwt?: boolean;
}