/**
 * JamApi
 * Api for JamServe
 *
 * OpenAPI spec version: 0.2.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {SessionUser} from 'src/app/services/jam/model/sessionUser';

export interface Session {
  /**
   * Api Version
   */
  version: string;
  allowedCookieDomains: Array<string>;
  /**
   * JSON Web Token
   */
  jwt?: string;
  user?: SessionUser;
}
