/**
 * JamApi
 * Api for JamServe
 *
 * OpenAPI spec version: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserRoles { 
    /**
     * User is Administrator
     */
    admin: boolean;
    /**
     * User has API Access
     */
    stream: boolean;
    /**
     * User can upload files
     */
    upload: boolean;
    /**
     * User can manage podcasts
     */
    podcast: boolean;
}